[project]
name = "mlops-practitioner-course"
version = "0.1.0"
description = "Sentiment Analysis MLOps Course Project"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "torch",
    "transformers",
    "scikit-learn",
    "pandas<3.0.0",
    "numpy",
    "mlflow",
    "fastapi",
    "uvicorn",
    "pydantic",
    "pydantic-settings",
    "emoji",
    "nltk",
    "requests"
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
